# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  # aliased to a recent 5.3.x version
  - 5.3
  # aliased to a recent 5.4.x version
  - 5.4
  # aliased to a recent 5.5.x version
  - 5.5

before_script:
  - composer install

# omitting "script:" will default to phpunit
script: phpunit --coverage-text

after_script:
  - CODECLIMATE_REPO_TOKEN=29a82fa40c275c4f0284dbec38223289e64c77b3a6faf5ca68c1c0e6127a0d86 php ./vendor/bin/test-reporter --stdout > codeclimate.json
  - curl -X POST -d @codeclimate.json -H 'Content-Type:application/json' -H 'User-Agent:Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports
